#If you modify anything in this config, all comments and notations will be removed.
#You can view an online version of this at https://github.com/MSWS/CustomEnchants/blob/master/config.yml

#############################
#                           #
#      Global Settings      #
#                           #
#############################

#How status messages will be sent.
#ACTIONBAR: Messages will be sent via the action bar
#CHAT: Messages will be sent via chat - May get spammy
StatusMessages: ACTIONBAR #Options: ACTIONBAR, CHAT

HelpLength: 10 #Unused

#NPC Settings
NPC:
  Type: VILLAGER #The EntityType that the entity will be
  Name: '&a&lEnchanter' #The name that will be visible above the NPC's head
  AllowRightClick: true
  AllowLeftClick: true

#What should the economy be called (you will have to customize this in guis.yml)
EconomyName: Token%s%
#What sort of economy/currency should be used? TOKEN is CustomEnchant's custom currency
#Swap to vault if you want to use with Essentials or other Vault compatible plugins
EconomyType: TOKEN #Options: TOKEN, VAULT

#What blocks will autosmelt affect?
#For example, IRON_ORE will be changed into IRON_INGOT
AutoSmeltDrops:
  IRON_ORE: IRON_INGOT
  GOLD_ORE: GOLD_INGOT
  COBBLESTONE: STONE

#What world(s) will certain enchantments be disabled in?
DisabledWorlds:
  All: #All enchantments will be disabled in these worlds
  - world_nether
  excavation: #The excavation enchantment will be disabled in these worlds
  - world_the_end
 #autograb: #(This would disable autograb in the "nograbbing" world)
 #- nograbbing

#############################
#                           #
#      Sound Settings       #
#                           #
#############################
Sounds:
  GoToMain:
    Name: BAT_LOOP
    Volume: 2
    Pitch: 2
  PurchasedEnchantment: #In /enchanter GUI
    Name: LEVEL_UP
    Volume: 2
    Pitch: 2
  SelectedEnchantment: #In /redeem GUI
    Name: CLICK
    Volume: 2
    Pitch: 2
  InsufficientFunds:
    Name: VILLAGER_NO
    Volume: 2
    Pitch: 2
  IterateLevels:
    Name: NOTE_PLING
  NextInventory:
    Name: CLICK
    Volume: 1
    Pitch: 2
  EnchantmentAdded:
    Name: LEVEL_UP
    Volume: 2
    Pitch: 1
  OpenEnchantmentInventory:
    Name: ANVIL_USE
    Volume: 1
    Pitch: 2

#############################
#                           #
#       GUI Settings        #
#                           #
#############################    
EnchantmentSuffix:
  Level:
  - ''
  - '&7(Right-Click to go up to &e%level% levels&7)'
  Price:
  - ''
  - '&a&lPrice: &a%price% Token%s%'
DefaultSpawnedItemsType: 'COMMAND'
NoTokens:
  Icon: 'BARRIER'
  Name: '&c&lNo tokens'
  Lore:
  - '&7You do not have any'
  - '&7redeemable tokens'
  - ''
  - '&7Purchase some with &a/enchanter'
TokenTitle: '&e&lEnchantment Token'

#############################
#                           #
#   Enchantment Settings    #
#                           #
#############################

#Probability:
#  1: 5 #The level I enchantment will have a %5 chance of activating
#  2: 10 #The level II enchantment will have a %10 chance of activating
#  5: 20 #The level V enchantment will have a %20 chance of activating
# Levels III - IV will have a %10 percent as it is the closest lowest specificed chance 

WitherPoint:
  Affects:
    Generic: true #If unspecified, should WitherPoint affect it?
    CREEPER: true #Should WitherPoint affect Creepers?
    PLAYER: true #Should WitherPoint affect Players?
   #ZOMBIE: false #(This would make WitherPoint not affect Zombies)
  Probability:
    1: 2
    2: 4
    3: 5
    4: 10
    5: 12
  SecondsPerLevel: 5000
  EffectType: WITHER
  Amplifier:
    1: 0
    3: 1
  SuccessMessage: '&e&l* * * &8&l[&f&lWITHERED&8&l] &e&l* * *' #Set to '' to disable, you can safely remove this line
Excavation:
  BonusAmount: #The radius that each level will break
    1: 3
    2: 5
    3: 7
  PlayEffect: true #If true the server will play a block break effect
  AllowCreative: false
  IteratePer: 1 #Ticks, 20 ticks in a second
  MaxBlocks: 500 #Maximum blocks to change per iteration
  DontBreak: #Blocks that excavation won't break
  - BEDROCK
  - OBSIDIAN
Rage:
  Multiplier: 1.1
  ResetAfterKill: true #If true then the multiplier will be reset once the player kills an entity
ToxicPoint:
  Affects:
    Generic: true
    CREEPER: true
    PLAYER: true
  Probability:
    1: 5
    2: 10
    3: 12
    4: 15
    5: 20
  SecondsPerLevel: 5000
  EffectType: POISON
  Amplifier:
    1: 0
  SuccessMessage: '&e&l* * * &8&l[&5&lPOISONED&8&l] &e&l* * *'
Freeze:
  Affects:
    Generic: true
    CREEPER: true
    PLAYER: true
  Probability:
    1: 5
    2: 7
    3: 10
    4: 13
    5: 15
  SecondsPerLevel: 5000
  EffectType: SLOW
  Amplifier:
    1: 0
  SuccessMessage: '&e&l* * * &8&l[&d&lSLOWNESS&8&l] &e&l* * *'
Revive:
  MinimumHealth: 5 #The minimum level of health (0-20) that is required for the enchantment to work
  BonusAmount: #How much health points each level should restore
    1: 3
    2: 5
    3: 8
  Probability:
    1: 5
    2: 10
    3: 15
    4: 17
    5: 20
  SuccessMessage: '&e&l* * * &8&l[&a&lREGENERATED&8&l] &e&l* * *'
StormBreaker:
  Probability:
    1: 1
    2: 2
    3: 5
    4: 10
    5: 15
  SuccessMessage: '&e&l* * * &8&l[&e&lSMITED&8&l] &e&l* * *'
Nightshade:
  Affects:
    Generic: true
    CREEPER: true
    PLAYER: true
  Probability:
    1: 5
    2: 7
    3: 10
    4: 13
    5: 15
  SecondsPerLevel: 5000
  EffectType: BLINDNESS
  Amplifier:
    1: 0
    4: 2
    5: 3
  SuccessMessage: '&e&l* * * &8&l[&7&lBLINDED&8&l] &e&l* * *'
Severed:
  Probability:
    1: 1
    2: 2
    3: 4
    4: 5
    5: 10
  SuccessMessage: '&e&l* * * &8&l[&3&lSKULL DROP&8&l] &e&l* * *'
Hearty:
  BonusAmount: #Note that this effect stacks with multiple pieces of armor
    1: 2
    2: 4
    3: 5.5
    4: 6
Spring:
  EffectType: JUMP
  Amplifier:
    1: 0
    2: 1
    3: 2
HeatShield:
  EffectType: FIRE_RESISTANCE
  Amplifier:
    1: 0
Summoner:
  Probability:
    1: 5
    2: 10
  EntityType: IRON_GOLEM #It is recommended to set this to a Creature, one that can target Players
  #(Examples: Iron golem, wolves, snowmen, etc.)
  BonusAmount:
    1: 1
    2: 2
  SuccessMessage: '&e&l* * * &8&l[&7&lSUMMONED&8&l] &e&l* * *'
Stun:
  Probability:
    1: 10
    2: 15
    3: 20
  BonusAmount: #How long each level will stun the target in milliseconds
    1: 3000
  SuccessMessage: '&e&l* * * &8&l[&e&lSTUNNEDD&8&l] &e&l* * *'
WitherShot:
  SecondsPerLevel: 5000
  EffectType: WITHER
  Probability:
    1: 10
    2: 20
  Amplifier:
    1: 0
    3: 1
  SuccessMessage: '&e&l* * * &8&l[&f&lWITHERED&8&l] &e&l* * *'
ToxicShot:
  SecondsPerLevel: 5000
  EffectType: POISON
  Probability:
    1: 5
    2: 20
  Amplifier:
    1: 0
    3: 1
  SuccessMessage: '&e&l* * * &8&l[&5&lPOISONED&8&l] &e&l* * *'
Barrage:
  RequireFullCharge: true
  UseInventoryArrows: true
  AllowInfinity: true
  OffsetInaccuracy: .5 #The distance between each arrow
  Spread: 1.0 #The spread of the arrows
  Speed: 3.0 #The speed of the arrows
  BonusAmount: #How many extra arrows will be shot per level
    1: 2
    2: 3
    3: 5
ExtraXP:
  MustBeSolid: true #If true then the mined block must be solid
  Probability: #The probability (per block) to reward the player
    1: 5
    2: 8
    3: 10
    4: 12
    5: 15
  BonusAmount: #The amount of XP to reward
    1: 1
    3: 2
    5: 3
  SuccessMessage: '&e&l* * * &8&l[&a&lXP GAINED&8&l] &e&l* * *'
SelfDestruct:
  BreakBlocks: false
  BonusAmount: #Explosion power
    1: 1
    2: 2
    3: 3
EnderShot:
  Cooldown:
    Actionbar:
      Enabled: true
      Message: '%bar% &7%time%'
      CompleteMessage: '&5&lENDERSHOT &e&lREFRESHED'
      Bar:
        Length: 20
        ProgChar: "&c\u258D"
        LeftChar: "&4\u258D"
    Sound:
      Enabled: true
      Name: NOTE_PLING
      Pitch: 2
      Volume: 2
    Chat:
      #Message: '&5&l[&5EnderShot &erefreshed&5&l]'
  TeleportSound:
    Enabled: true
    Name: ENDERMAN_TELEPORT
    Pitch: 1
    Volume: 2
  DeleteArrow: true
  BonusAmount: #Cooldown duration (in milliseconds)
    1: 20000
    2: 18000
    3: 15000
    4: 12000
    5: 10000
Burning:
  Probability:
    1: 5
    2: 10
    3: 15
    4: 20
    5: 25
  BonusAmount: #Fireticks per level (20 ticks in a second)
    1: 20
    2: 30
    3: 40
    4: 80
    5: 100
  SuccessMessage: '&e&l* * * &8&l[&6&lENFLAMED&8&l] &e&l* * *'