name: CustomEnchants
main: org.mswsplex.enchants.msws.CustomEnchants
version: 1.0
description: Custom Enchants coded for Blitz Network
commands:
  enchanter:
    usage: /<command>
  addenchant:
    usage: /<command> [Enchantment|All]
  token:
    usage: /<command>
  redeem:
    usage: /<command>
  giveenchant:
    usage: /<command> [Player] [Enchantment] <Level>