name: FreakyEnchants
main: org.mswsplex.enchants.msws.FreakyEnchants
version: 1.0.1
description: Freaky Enchantments created by MSWS
softdepend:
- Vault
- WorldGuard
- PlaceholderAPI
commands:
  enchanter:
    usage: /<command>
  addenchant:
    usage: /<command> [Enchantment|All]
  token:
    usage: /<command>
  redeem:
    usage: /<command>
  giveenchant:
    usage: /<command> [Player] [Enchantment] <Level>